### ISSUE TITLE
PostgreSQL arrays are treated as strings

### ISSUE THREAD

**Issue by jigish** [algolia/jdbc-java-connector#6]
I tried using this to insert some records into my index and it seems like PostgreSQL arrays are actually treated as strings when they are inserted.

I have an index called "people" in my account (jigish@accompani.com) which shows the issue. The select statement I used selects an array of text as "_tags" but the _tags field shows up as a string in PostgreSQL array format (e.g. "{string1,string2,string3}"). I'll leave the index in my account if you want to take a look yourself.

Thanks for all the help!

**Comment by Nagriar** [comment]
@jigish thanks!
